version: "3.8"

services:
  remote:
    image: dvc-http-remote
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOSTNAME=localhost
      - PATH_PREFIX=/remote
      - UPLOAD_BUFFER_SIZE=10485760
      - AZURE_STORAGE_URL=azure://test/
      - AZURE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=...
